### ISSUE TITLE
Take along cluster resource labels

### ISSUE THREAD

**Issue by siredmar** [dntosas/capi2argo-cluster-operator#221]
Hi!

it would be nice if certain labels of the cluster resource can be taken along to the ArgoCD secret. This can be useful if you've configured ArgoCD to deploy certain stuff only on clusters with certain labels, e.g. `env: stage` or `env: prod`.

Could be configurable via a label in the cluster resource like `take-along-label.capi-to-argocd.<key>=`
One has to read the cluster resource and get the labels and put them on the ArgoCD secret according to the take-along label.

Example for the cluster resource: 
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata: 
  labels: 
    cloudprovider.clusters.infrastructure.edgefarm.io/type: hetzner
    clusters.infrastructure.edgefarm.io/type: core
    core.edgefarm.io/name: dog
    env: stage
    deploy: group1
    foo: bar
    take-along-label.capi-to-argocd.env: ""
    take-along-label.capi-to-argocd.deploy: ""
  name: dog
  namespace: default
...
```

And the resulting secret:

```yaml
kind: Secret
metadata: 
  labels: 
    argocd.argoproj.io/secret-type: cluster
    capi-to-argocd/cluster-namespace: coreclusters
    capi-to-argocd/cluster-secret-name: dog-kubeconfig
    capi-to-argocd/owned: "true"
    env: stage
    deploy: group1
  name: cluster-dog
  namespace: argocd
...
```

@dntosas what do you think?

Update: changed `take-along-label.capi-to-argocd/<key>` to `take-along-label.capi-to-argocd-<key>`, because k8s label prevents from setting multiple `/`. This is the case when taking a long label along e.g. `my.domain.com/subdomain`. Using the `/` as delimiter it would look like this `take-along-label.capi-to-argocd/my.domain.com/subdomain` which is invalid.
